Fix publish docker images workflow

diff --git a/.github/workflows/publish-docker-images.yml b/.github/workflows/publish-docker-images.yml
--- a/.github/workflows/publish-docker-images.yml
+++ b/.github/workflows/publish-docker-images.yml
@@ -20,11 +20,13 @@ jobs:
       - name: Get the tag name
         id: get_tag
         run: |
-          tag=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
-          dist_tag=$([[ $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo latest || echo "")
-          dist_tag=$([[ $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]] && echo rc || echo $dist_tag)
-          [ -z "$dist_tag" ] && echo "Distribution tag is not set to latest nor to rc" && exit 1
-          echo ::set-output name=DIST_TAG::$dist_tag
+          tag=${GITHUB_REF/refs\/tags\//}
+          if [[ $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?$ ]]; then
+            echo "DIST_TAG=$tag" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid tag format: $tag" >&2
+            exit 1
+          fi
         shell: bash
   publish:
     runs-on: ubuntu-latest
